# Generated by Django 4.2.4 on 2023-10-21 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_remove_appmodel_email_remove_appmodel_message_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appmodel',
            old_name='E-mail',
            new_name='Email',
        ),
    ]
